In [ ]:
import torch
image_tensor=torch.rand(224,224,3)
print(image_tensor)
print(image_tensor.shape)
print(image_tensor.ndim)

tensor([[[0.6767, 0.5667, 0.6698],
         [0.8716, 0.7979, 0.5570],
         [0.7117, 0.2006, 0.8408],
         ...,
         [0.7934, 0.4124, 0.6104],
         [0.6571, 0.6140, 0.6300],
         [0.1005, 0.8547, 0.6324]],

        [[0.0656, 0.6958, 0.9423],
         [0.1908, 0.7510, 0.0322],
         [0.1915, 0.0076, 0.8175],
         ...,
         [0.9214, 0.7203, 0.3244],
         [0.0413, 0.0936, 0.9703],
         [0.7861, 0.8547, 0.8740]],

        [[0.8104, 0.9820, 0.2868],
         [0.3211, 0.6344, 0.0936],
         [0.9397, 0.1075, 0.2253],
         ...,
         [0.2463, 0.9648, 0.3125],
         [0.6128, 0.9145, 0.4546],
         [0.3168, 0.6374, 0.3000]],

        ...,

        [[0.5054, 0.1983, 0.0080],
         [0.4831, 0.4032, 0.6667],
         [0.2907, 0.1194, 0.0167],
         ...,
         [0.6792, 0.8708, 0.2135],
         [0.4616, 0.5192, 0.2077],
         [0.2920, 0.5011, 0.8764]],

        [[0.2731, 0.0574, 0.3337],
         [0.9716, 0.2080, 0.0668],
         [0.

In [ ]:
range=torch.arange(start=1,end=10,step=2)
range

tensor([1, 3, 5, 7, 9])

In [ ]:
ran=torch.tensor([3,6,9],
                 dtype=float,
                 device='cpu',
                 requires_grad=False)
ran,ran.shape,ran.device

(tensor([3., 6., 9.], dtype=torch.float64),
 torch.Size([3]),
 device(type='cpu'))